version: '3'
services:
  mysql-stock:
    image: 'mysql/mysql-server:5.7.25'
    volumes:
      - /var/lib/stock_data
    environment:
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_DATABASE=bpm-db
      - MYSQL_USER=hust
      - MYSQL_PASSWORD=hust@1234
    ports:
      - "3307:3306"
#  stock-api:
#    image: stock-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-stock:3306/stock-db?useUnicode=yes&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: "hust"
#      SPRING_DATASOURCE_PASSWORD: "hust@1234"
#    build:
#      context: "./"
#      dockerfile: "Dockerfile"
#    depends_on:
#      - mysql-stock
#  stock-job:
#    image: stock-job
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-stock:3306/stock-db?useUnicode=yes&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: "hust"
#      SPRING_DATASOURCE_PASSWORD: "hust@1234"
#    build:
#      context: "./"
#      dockerfile: "Dockerfile"
#    depends_on:
#      - mysql-stock
#  zookeeper:
#    container_name:
#      zookeeper_merge
#    image:
#      wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    container_name:
#      kafka_merge
#    image:
#      wurstmeister/kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "TOPIC-DEMO"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock