server:
  port: 8081
  ssl:
    enabled: false

server.servlet.contextPath: /stock-app/v1
#logging.config: stock-app/config/log4j2.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.servlet.multipart.enabled: false
#spring.servlet.multipart.resolve-lazily: false
abc: myname

files:
  folder: stock-app/template/
spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database: MYSQL
    show-sql: true
    format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    generate_statistics: true
  datasource:
    platform: mysql
    url: jdbc:mysql://13.68.193.134:3306/stockdb?allowPublicKeyRetrieval=true&useSSL=false
    username: hust
    password: hust@1234
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3000000
      # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
stock.bds: "VIC,VHM,VRE,PRD,KDH,REE,DXG,HDG,FLC,ITA"
stock.ck: "SSI,VND,VCI,HCM,MBS,FTS,SHS,KLB,AGR,TVS"
stock.cn:  "FPT,FOX,CMG,SAM,SGT,ELC,VEC,ITD,TTN,CNC"
stock.dp: "DGC,DHG,DVN,IMP,TRA,DMC,CSV,DCL,VFG,OPC"
stock.hk: "ACV,VJC,HVN,SAS,SGN,NCT,NCS,MAS,NAS,ARM"
stock.bank: "VCB,TCB,BID,CTG,MBB,VPB,ACB,SHB,STB,TPB,BVH,VIB,HDB,EIB,LPB,BAB,NVB,ABB,PVI,VBB"
stock.xd: "VCG,DIG,DXG,CTD,HBC,ROS,VCP,VLB,TV2,CC1"
stock.dk: "GAS,BSR,PLX,PVS,PVD,PVI,PVT,PLC,PET,PGS"
stock.nhua: "NTP,BMP,AAA,DNP,SVI,INN,RDP,HII,VNP,MCP"
stock.common: "VNINDEX,HSX,HNX,VN100,VN70,VN30"