server:
  port: 8081
  ssl:
    enabled: false

server.servlet.contextPath: /stock-app/v1
#logging.config: stock-app/config/log4j2.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.servlet.multipart.enabled: false
#spring.servlet.multipart.resolve-lazily: false
abc: myname

files:
  folder: stock-app/template/
spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database: MYSQL
    show-sql: true
    format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/stockdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root@1234
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000
      # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
stock.vn100: "ACB,BID,BVH,CTG,FPT,GAS,GVR,HDB,HPG,KDH,MBB,MSN,MWG,NVL,PDR,PLX,PNJ,POW,SAB,SSI,STB,TCB,TPB,VCB,VHM,VIC,VJC,VNM,VPB,VRE,REE,VNINDEX"
