server:
  port: 8081
  ssl:
    enabled: false

server.servlet.contextPath: /stock-app/v1
#logging.config: stock-app/config/log4j2.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.servlet.multipart.enabled: false
#spring.servlet.multipart.resolve-lazily: false
abc: myname
files:
  folder: stock-app/template/
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database: MYSQL
    show-sql: true
    format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.66.125:3306/stockdb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: cmcdu21
    password: cmc@du21
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
bezkoder:
   app:
       jwtSecret: bezKoderSecretKey
       jwtExpirationMs: 86400000
