server:
  port: 8090
  ssl:
    enabled: false
spring.rabbitmq.host : localhost
spring.rabbitmq.port : 8091
spring.rabbitmq.username : guest
spring.rabbitmq.password : guest
javainuse.rabbitmq.exchange : javainuse.exchange
javainuse.rabbitmq.queue : javainuse.queue
javainuse.rabbitmq.routingkey : javainuse.routingkey

#server.servlet.contextPath:
#eureka:
#  client:
#  registerWithEureka: false
#  fetchRegistry: false
#logging.config: stock-gw/config/log4j2.xml
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
##spring.servlet.multipart.enabled: false
##spring.servlet.multipart.resolve-lazily: false
#
#spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#  jpa:
#    database: MYSQL
#    show-sql: true
#    format_sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: update
#  datasource:
#    platform: mysql
#    url: jdbc:mysql://103.107.183.148:3307/stock-db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#    username: hust
#    password: hust@1234
#  database:
#    driver-class-name: com.mysql.cj.jdbc.Driver
