Configuration:
  status: warn
  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: '%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level - [%t] %c{1} - %m%n'
    RollingRandomAccessFile:
      - name: INFO
        fileName: log/stcok-gw.log
        filePattern: log/$${date:yyyy-MM}/%d{yyyy-MM-dd}-stock-gw-%i.log.gz
        PatternLayout:
          pattern: '%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level - [%t] %c{1} - %m%n'
        Policies:
          TimeBasedTriggeringPolicy: {
          }
          OnStartupTriggeringPolicy: {
          }
          SizeBasedTriggeringPolicy:
            size: 200 MB
      - name: ERROR
        fileName: log/bond-api-error.log
        filePattern: log/$${date:yyyy-MM}/%d{yyyy-MM-dd}-stock-gw-error-%i.log.gz
        PatternLayout:
          pattern: '%d{yyyy/MM/dd HH:mm:ss.SSS} %-5level - [%t] %c - %m%n'
        Policies:
          TimeBasedTriggeringPolicy: {
          }
      - name: JSON
        fileName: log/bond-api.json
        filePattern: log/$${date:yyyy-MM}/%d{yyyy-MM-dd}-stock-gw-%i.json.gz
        JSONLayout:
          stacktraceAsString: true
          compact: true
          eventEol: true
        Policies:
          TimeBasedTriggeringPolicy: {
          }
          OnStartupTriggeringPolicy: {
          }
          SizeBasedTriggeringPolicy:
            size: 200 MB
  Loggers:
    Logger:
      - name: EventLogger
        level: info
        additivity: false
        AppenderRef:
          - ref: ERROR
          - ref: INFO
          - ref: JSON
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ERROR
          level: error
        - ref: INFO
        - ref: JSON